version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk
    steps:
      
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Tests!
          command: dotnet test \Tests
      - run:
          name: Store Test Results
          command: store_test_results
          path: /