version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Tests!
          command: dotnet test \Tests -xml $CIRCLE_ARTIFACTS/junit.xml